const activities = [
  ['13-Min Helicopter Flight','Flights','$204','12–13 min','See the Falls from above on a scenic figure-eight flight.','Laina-Light-Tours-Activities-Images-Copilot/activities/13-min-helicopter-flight-01.jpeg'],
  ['Explore the Zambezi Flight','Flights','$249','22 min','Follow the Falls, Batoka Gorge and river islands from the air. $50 government/fuel surcharge charged separately.','Laina-Light-Tours-Activities-Images-Copilot/activities/explore-the-zambezi-flight.jpeg'],
  ['15-Min Microlight Flight – Zambia','Flights','$221','15 min','A quiet, open-air view across the Zambezi landscape.','Laina-Light-Tours-Activities-Images-Copilot/activities/15-min-microlight-flight-zambia.jpeg'],
  ['Full Day Chobe','Safari','$175','10–11 hrs','A border-crossing day of river cruising, game drives and lunch.','More Images/Chobe Game Drive.avif'],
  ['Game Drive','Safari','$102','3–3.5 hrs','Track wildlife through Zambezi National Park with a local guide.','Laina-Light-Tours-Activities-Images-Copilot/activities/game-drive-4x4.jpeg'],
  ['Elephant Interaction','Safari','$180','—','An up-close conservation experience with gentle giants.','Laina-Light-Tours-Activities-Images-Copilot/activities/elephant-interaction.jpeg'],
  ['Riversong Sunset Cruise','Cruises','$89','2–2.5 hrs','Premium drinks, golden light and the river doing what it does best.','Laina-Light-Tours-Activities-Images-Copilot/activities/riversong-sunset-cruise.jpeg'],
  ['Zambezi Sunset Cruise','Cruises','$64','2–2.5 hrs','A relaxed sunset and wildlife cruise with local drinks and snacks.','Laina-Light-Tours-Activities-Images-Copilot/activities/zambezi-sunset-cruise.jpeg'],
  ['Dinner Cruise','Cruises','$128','Evening','Drift into the evening with dinner on the Zambezi.','More Images/Sunset Cruise.avif'],
  ['Big Air Experience','Adrenaline','$280','45–60 min','Bungee, swing and slide: the whole bridge-day story in one.','More Images/Big Air Experience.avif'],
  ['Bridge Swing – Tandem','Adrenaline','$201','15–20 min','A giant pendulum swing over the Batoka Gorge.','Laina-Light-Tours-Activities-Images-Copilot/activities/bridge-swing-tandem.webp'],
  ['White Water Rafting – Day Trip','Water','$186','6 hrs','Grade 5 rapids and a full day in the Batoka Gorge.','Laina-Light-Tours-Activities-Images-Copilot/activities/white-water-rafting-day-trip.jpeg'],
  ['Jet Boat Adventure','Water','$153','2.5 hrs','Fast water, deep gorge and a 465hp jet boat.','Laina-Light-Tours-Activities-Images-Copilot/activities/jet-boat-adventure.jpeg'],
  ['Canopy Tour','Water','$86','—','Glide through the forest canopy above the Zambezi.','More Images/Canopy Tour.jpg'],
  ['Victoria Falls Guided Rainforest Tour','Culture','$88','2–2.5 hrs','Walk the rainforest viewpoints with an expert guide.','Laina-Light-Tours-Activities-Images-Copilot/activities/victoria-falls-guided-rainforest-tour.jpeg'],
  ['Boma Dinner & Drum Show','Culture','$80','Evening','A generous, rhythmic night of food, stories and performance.','More Images/Boma Dinner.jpg'],
  ['Livingstone Island Lunch – Zambia','Cruises','$240','—','Lunch at the edge of the Zambezi, on Livingstone Island.','More Images/Livingstone Island lunch.webp'],
  ['Rhino Safari – Zambia','Safari','$125','—','A conservation-led safari in Mosi-oa-Tunya National Park.','More Images/Rhino Safari.avif']
];

const grid = document.querySelector('#activity-grid');
const search = document.querySelector('#activity-search');
const category = document.querySelector('#category-filter');
const count = document.querySelector('#result-count');
function renderActivities(){
  if(!grid) return;
  const term=(search?.value||'').toLowerCase(); const filter=category?.value||'All categories';
  const visible=activities.filter(a=>(filter==='All categories'||a[1]===filter)&&a[0].toLowerCase().includes(term));
  count.textContent=visible.length;
  grid.innerHTML=visible.map((a,i)=>`<article class="activity-card" data-index="${activities.indexOf(a)}"><div class="activity-card-image"><img src="${a[5]}" alt="${a[0]}"><span class="activity-category">${a[1]}</span></div><div class="activity-details"><h3>${a[0]}</h3><p>${a[4]}</p><div class="activity-bottom"><strong class="activity-price">${a[2]}</strong><span class="activity-duration">${a[3]}</span><button class="activity-add" type="button" aria-label="Add ${a[0]} to itinerary">+</button></div></div></article>`).join('');
  grid.querySelectorAll('.activity-card').forEach(card=>{const activity=activities[card.dataset.index];card.addEventListener('click',()=>openModal(activity));card.querySelector('.activity-add').addEventListener('click',event=>{event.stopPropagation();addToItinerary(activity[0],event.currentTarget);});});
}
function addToItinerary(name,button){const selected=JSON.parse(localStorage.getItem('lainaSelections')||'[]');if(!selected.includes(name)){selected.push(name);localStorage.setItem('lainaSelections',JSON.stringify(selected));}button.textContent='✓';button.classList.add('added');updateItineraryNav();}
function openModal(a){const modal=document.querySelector('#activity-modal'); if(!modal)return; document.querySelector('#modal-image').src=a[5]; document.querySelector('#modal-image').alt=a[0]; document.querySelector('#modal-category').textContent=a[1]; document.querySelector('#modal-title').textContent=a[0]; document.querySelector('#modal-description').textContent=a[4]; document.querySelector('#modal-price').textContent=a[2]; document.querySelector('#modal-duration').textContent=a[3];document.querySelector('#add-itinerary').onclick=()=>addToItinerary(a[0],document.querySelector('#add-itinerary')); modal.classList.add('open');modal.setAttribute('aria-hidden','false');}
function closeModal(){const modal=document.querySelector('#activity-modal');if(modal){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}}
if(grid){const params=new URLSearchParams(location.search);if(params.get('category'))category.value=params.get('category');renderActivities();search.addEventListener('input',renderActivities);category.addEventListener('change',renderActivities);document.querySelector('.modal-close').addEventListener('click',closeModal);document.querySelector('#activity-modal').addEventListener('click',e=>{if(e.target.id==='activity-modal')closeModal()});}
const booking=document.querySelector('#booking-form');if(booking)booking.addEventListener('submit',e=>{e.preventDefault();const date=booking.querySelector('input[type="date"]')?.value;if(date)localStorage.setItem('lainaDates',JSON.stringify({arrival:date}));document.querySelector('#booking-message').textContent='Lovely. We will shape a first draft of your adventure and be in touch shortly.'});
document.querySelectorAll('.newsletter-form').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();form.innerHTML='<p style="color:white;margin:15px 0;font-size:13px">You are on the list. See you out there.</p>'}));
document.querySelectorAll('.menu-toggle').forEach(btn=>btn.addEventListener('click',()=>{const nav=document.querySelector('.main-nav');nav.style.display=nav.style.display==='flex'?'none':'flex';nav.style.position='absolute';nav.style.top='70px';nav.style.left='0';nav.style.right='0';nav.style.padding='20px 25px';nav.style.background='var(--cream)';nav.style.flexDirection='column';nav.style.gap='18px'}));
const siteHeader=document.querySelector('.site-header');
if(siteHeader){const updateHeader=()=>siteHeader.classList.toggle('scrolled',window.scrollY>36);updateHeader();window.addEventListener('scroll',updateHeader,{passive:true});}
function updateItineraryNav(){document.querySelectorAll('.itinerary-nav-count').forEach(item=>item.textContent=JSON.parse(localStorage.getItem('lainaSelections')||'[]').length)}
updateItineraryNav();
const revealTargets=document.querySelectorAll('.benefits-bar,.packages-section,.discover,.split-section,.quote-section,.customizer-section');
if(revealTargets.length&&'IntersectionObserver' in window){const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');revealObserver.unobserve(entry.target)}}),{threshold:.12});revealTargets.forEach(target=>revealObserver.observe(target));}
document.querySelectorAll('.search-tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.search-tab').forEach(item=>{item.classList.toggle('active',item===tab);item.setAttribute('aria-selected',item===tab?'true':'false')});const form=document.querySelector('#booking-form');if(form)form.dataset.mode=tab.dataset.bookingMode;const title=document.querySelector('.booking-intro h2');if(title)title.innerHTML=tab.dataset.bookingMode==='packages'?'Choose your<br><i>stay awhile.</i>':'Build your<br><i>perfect day.</i>'}));
const itineraryOptions=document.querySelectorAll('.customizer-option input');
if(itineraryOptions.length){const updateItinerary=()=>{const selected=[...itineraryOptions].filter(option=>option.checked).map(option=>option.value);localStorage.setItem('lainaSelections',JSON.stringify(selected));document.querySelector('#itinerary-count').textContent=`${selected.length} experience${selected.length===1?'':'s'} selected`;document.querySelector('#itinerary-list').textContent=selected.length?selected.join(' · '):'Select experiences to begin building your day.'};itineraryOptions.forEach(option=>option.addEventListener('change',updateItinerary));}
const itineraryList=document.querySelector('#selected-list');
if(itineraryList){const selected=JSON.parse(localStorage.getItem('lainaSelections')||'[]');const arrival=document.querySelector('#arrival-date');const departure=document.querySelector('#departure-date');const savedDates=JSON.parse(localStorage.getItem('lainaDates')||'{}');if(savedDates.arrival)arrival.value=savedDates.arrival;if(savedDates.departure)departure.value=savedDates.departure;const draw=()=>{const current=JSON.parse(localStorage.getItem('lainaSelections')||'[]');document.querySelector('#selection-count').textContent=current.length;itineraryList.innerHTML=current.length?current.map((item,index)=>`<div class="selected-item"><span>${index+1}. ${item}</span><button type="button" data-remove="${index}" aria-label="Remove ${item}">Remove</button></div>`).join(''):'<p class="empty-selection">No activities selected yet. Visit the activities page to add your first experience.</p>';itineraryList.querySelectorAll('[data-remove]').forEach(button=>button.addEventListener('click',()=>{const next=JSON.parse(localStorage.getItem('lainaSelections')||'[]');next.splice(Number(button.dataset.remove),1);localStorage.setItem('lainaSelections',JSON.stringify(next));draw()}))};draw();document.querySelector('#itinerary-form').addEventListener('submit',event=>{event.preventDefault();localStorage.setItem('lainaDates',JSON.stringify({arrival:arrival.value,departure:departure.value}));document.querySelector('#itinerary-success').textContent=`Your ${arrival.value} to ${departure.value} itinerary is ready for final review.`;});}
